services:
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=81
    links:
      - appointments.api
      - clinic.api
      - documents.api
      - notifications.api
      - profiles.api
      - services.api
    depends_on:
      - appointments.api
      - clinic.api
      - documents.api
      - notifications.api
      - profiles.api
      - services.api
    ports:
      - "5270:80"
      - "7047:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  clinic.api:
    container_name: clinic.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "82"
      ASPNETCORE_HTTPS_PORTS: "83"
      MongoDB__ConnectionURI: "mongodb://mongo:27017/"
      MongoDB__DatabaseName: "Offices"
    depends_on:
      - mongo
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  servicesdb:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: servicesdb
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password1!
   restart: always
   ports:
     - "1433:1433"
   volumes:
     - servicesdb:/var/lib/mssql/data/ 

  services.api:
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_HTTP_PORTS: "84"
     ASPNETCORE_HTTPS_PORTS: "85"
     TZ: "Europe/Moscow"
     ConnectionStrings:ServicesDbConnection: "Server=servicesdb,1433;Database=ServicesDB;User=SA;Password=Password1!;MultipleActiveResultSets=True;TrustServerCertificate=true"
   depends_on:
     - servicesdb
   ports:
     - "5159:84"
     - "7284:85"
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  profilesdb:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: profilesdb
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password1!
   restart: always
   ports:
     - "1434:1433"
   volumes:
     - profilesdb:/var/lib/mssql/data/ 

  profiles.api:
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_HTTP_PORTS: "86"
     ASPNETCORE_HTTPS_PORTS: "87"
     TZ: "Europe/Moscow"
     ConnectionStrings:ProfilesDbConnection: "Server=profilesdb,1434;Database=ProfilesDB;User=SA;Password=Password1!;MultipleActiveResultSets=True;TrustServerCertificate=true"
   depends_on:
     - profilesdb
   ports:
     - "5242:86"
     - "7081:87"
   volumes:
     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  documents.api:
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_HTTP_PORTS: "88"
     ASPNETCORE_HTTPS_PORTS: "89"
   ports:
     - "5007:88"
     - "7052:89"
   volumes:
     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit-host
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork

  notifications.api:
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_HTTP_PORTS: "90"
     ASPNETCORE_HTTPS_PORTS: "91"
     RabbitMq__RabbitMqHost: "rabbitmq"
     RabbitMq__RabbitMqQueue: "MyQueue"
     RABBITMQ_HOST: rabbitmq
     RABBITMQ_USER: user
     RABBITMQ_PASSWORD: password
   depends_on:
     - rabbitmq
   ports:
     - "5055:90"
     - "7262:91"
   volumes:
     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/
   networks:
      - mynetwork

  appointmentsdb:
   image: postgres:latest
   container_name: appointmentsdb
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: AppointmentsDb
   restart: always
   ports:
       - "5433:5432"
   volumes:
     - appointmentsdb:/var/lib/postgresql/data/ 
   networks:
      - mynetwork

  appointments.api:
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_HTTP_PORTS: "92"
     ASPNETCORE_HTTPS_PORTS: "93"
     RabbitMq__RabbitMqHost: "rabbitmq"
     RabbitMq__RabbitMqQueue: "MyQueue"
     RABBITMQ_HOST: rabbitmq
     RABBITMQ_USER: user
     RABBITMQ_PASSWORD: password
     ConnectionStrings:DefaultConnection: "Host=appointmentsdb;Port=5432;Database=AppointmentsDb;Username=postgres;Password=postgres"
   depends_on:
     - appointmentsdb
     - rabbitmq
   ports:
     - "5175:92"
     - "7045:93"
   volumes:
     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/
   networks:
      - mynetwork

  clinic-react-client:
    container_name: client.app
    depends_on:
      - gateway.api
    ports:
      - "5173:5173"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/
