services:
  servicesdb:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: servicesdb
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password1!
   restart: always
   ports:
     - "1433:1433"
   volumes:
     - servicesdb:/var/lib/mssql/data/ 

  services.api:
   environment:
     ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_HTTP_PORTS: "84"
     ASPNETCORE_HTTPS_PORTS: "85"
     TZ: "Europe/Moscow"
     ConnectionStrings:ServiceDbConnection: "Server=servicesdb,1433;Database=ServicesDB;User=SA;Password=Password1!;MultipleActiveResultSets=True;TrustServerCertificate=true"
   depends_on:
     - servicesdb
   ports:
     - "5159:84"
     - "7284:85"
   volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  #profilesdb:
  #  image: mcr.microsoft.com/mssql/server:2017-latest
  #  container_name: profilesdb
  #  environment:
  #    - SA_PASSWORD=Pass@word
  #    - ACCEPT_EULA=Y
  #  restart: always
  #  ports:
  #    - "1433:1433"
  #  volumes:
  #    - profilesdb:/var/lib/mssql/data/ 
      
  #appointmentsdb:
  #  container_name: appointmentsdb
  #  environment:
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  #    - POSTGRES_DB=AppointmentsDb
  #  restart: always
  #  ports:
  #      - "5433:5432"
  #  volumes:
  #    - appointmentsdb:/var/lib/postgresql/data/ 
      
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo:/data/db
  #     - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  #appointments.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_HTTP_PORTS=8080
  #    - ASPNETCORE_HTTPS_PORTS=8081
  #    - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=AppointmentsDb;User Id=postgres;Password=postgres;Include Error Detail=true
  #  depends_on:
  #    - appointmentsdb
  #  ports:
  #    - "5175:8080"
  #    - "7045:8081"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # clinic.api:
  #   container_name: clinic.api
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ASPNETCORE_HTTP_PORTS: "82"
  #     ASPNETCORE_HTTPS_PORTS: "83"
  #     MongoDB__ConnectionURI: "mongodb://mongo:27017/"
  #     MongoDB__DatabaseName: "Offices"
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
  #     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  #documents.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_HTTP_PORTS=8080
  #    - ASPNETCORE_HTTPS_PORTS=8081
  #  ports:
  #    - "5007:8080"
  #    - "7052:8081"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # gateway.api:
  #   container_name: gateway.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=80
  #     - ASPNETCORE_HTTPS_PORTS=81
  #   links:
  #     - clinic.api
  #   depends_on:
  #     #- appointments.api
  #     - clinic.api
  #     #- documents.api
  #     #- notifications.api
  #     #- profiles.api
  #     #- services.api
  #   ports:
  #     - "5270:80"
  #     - "7047:81"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
  #     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/

  #notifications.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_HTTP_PORTS=8080
  #    - ASPNETCORE_HTTPS_PORTS=8081
  #  ports:
  #    - "5055:8080"
  #    - "7262:8081"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro 

  #profiles.api:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_HTTP_PORTS=8080
  #    - ASPNETCORE_HTTPS_PORTS=8081
  #    - ConnectionStrings__Database=Server=profilesdb;Port=1433;Database=ProfilesDb;SA_PASSWORD=Pass@word;ACCEPT_EULA=Y
  #  depends_on:
  #    - profilesdb
  #  ports:
  #    - "5242:8080"
  #    - "7081:8081"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # clinic-react-client:
  #   container_name: client.app
  #   depends_on:
  #     - gateway.api
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets
  #     - ${USERPROFILE}/.aspnet/https:/home/app/.aspnet/https/
